POST http://localhost:8081/api/paystack/webhook
Content-Type: application/json
x-paystack-signature: webhook-laravel

{
    "event": "charge.success",
    "data": {
        "id": 12,
        "amount": 10000,
        "currency": "EUR",
        "status": "success",
        "reference": "ABC123456789"
    }
}

###

POST http://localhost:8081/api/paystack/webhook
Content-Type: application/json
x-paystack-signature: webhook-laravel

{
"event": "charge.error",
"data": {
"id": 12,
"amount": 10000,
"currency": "EUR",
"status": "success",
"reference": "ABC123456789"
}
}
